# postgtesql local db with default user & password. network: host
version: '3.7'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: curs
    ports:
      - 15432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
