-- Drop the tables
DROP TABLE IF EXISTS
  VEHICLE_OWNERSHIP,
  LOADING_UNLOADING_AGREEMENT,
  STORAGE_POINT,
  ADDRESS,
  CARGO,
  ORDER_STATUSES,
  ORDERS,
  VEHICLE_MOVEMENT_HISTORY,
  VEHICLE,
  DRIVER_LICENSE,
  DRIVER_STATUS_HISTORY,
  TARIFF_RATE,
  FUEL_CARDS_FOR_DRIVERS,
  DRIVER,
  CUSTOMER,
  CONTACT_INFO,
  PERSON
  CASCADE;

-- Drop the types
DROP TYPE IF EXISTS
  DRIVER_STATUS,
  BODY_TYPE,
  CARGO_TYPE,
  ORDER_STATUS,
  CONTACT_INFO_TYPE;

