###
GET http://localhost:8080/index

###
POST http://localhost:8080/add_customer
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "Smith",
  "gender": "M",
  "dateOfBirth": "2023-12-06"
}

###
POST http://localhost:8080/add_driver
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "Smith",
  "gender": "M",
  "dateOfBirth": "2023-12-06",
  "passport": "0234567890",
  "bankCardNumber": "1234567890123456"
}

###
POST http://localhost:8080/add_driver_info
Content-Type: application/json

{
  "driverId": 11,
  "dailyRate": 100,
  "ratePerKm": 10,
  "issueDate": "2003-12-06",
  "expirationDate": "2028-12-06",
  "licenseNumber": 1234567890123456,
  "fuelCard": "123456789012345",
  "fuelStationName": "1234567890123456"
}

###
POST http://localhost:8080/add_order
Content-Type: application/json

{
  "distance": 100,
  "weight": 99,
  "width": 1,
  "height": 1,
  "length": 1,
  "cargoType": "BULK",
  "latitude": 47.5,
  "longitude": 23.54,
  "departurePointId": 1001,
  "deliveryPointId": 1002,
  "senderId": 1,
  "receiverId": 1,
  "unloadingTime": 3,
  "loadingTime": 3
}

###
POST http://localhost:8080/add_storagepoint
Content-Type: application/json

{
    "name": "test",
    "country": "test",
    "city": "test",
    "street": "test",
    "building": 1,
    "corpus": 1,
    "latitude": 47.5,
    "longitude": 23.54
}

###
POST http://localhost:8080/add_storagepoint
Content-Type: application/json

{
    "name": "test2",
    "country": "test",
    "city": "test2",
    "street": "test2",
    "building": 1,
    "corpus": 1,
    "latitude": 47.9,
    "longitude": 23.84
}

###
GET http://localhost:8080/orders?pageNumber=0&pageSize=2