###
GET http://localhost:8080/index

###
POST http://localhost:8080/add_customer
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "Smith",
  "gender": "M",
  "dateOfBirth": "2023-12-06"
}

###
POST http://localhost:8080/add_driver
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "middleName": "Smith",
  "gender": "M",
  "dateOfBirth": "2023-12-06",
  "passport": "0234567890",
  "bankCardNumber": "1234567890123456"
}

###
POST http://localhost:8080/add_driver_info
Content-Type: application/json

{
  "driverId": 11,
  "dailyRate": 100,
  "ratePerKm": 10,
  "issueDate": "2003-12-06",
  "expirationDate": "2028-12-06",
  "licenseNumber": 1234567890123456,
  "fuelCard": "123456789012345",
  "fuelStationName": "1234567890123456"
}

###
POST http://localhost:8080/add_order
Content-Type: application/json

{
  "distance": 100,
  "weight": 99,
  "width": 1,
  "height": 1,
  "length": 1,
  "cargoType": "BULK",
  "latitude": 47.5,
  "longitude": 23.54,
  "departurePointId": 1001,
  "deliveryPointId": 1002,
  "senderId": 1,
  "receiverId": 1,
  "unloadingTime": 3,
  "loadingTime": 3
}

###
POST http://localhost:8080/add_storagepoint
Content-Type: application/json

{
  "name": "test",
  "country": "test",
  "city": "test",
  "street": "test",
  "building": 1,
  "corpus": 1,
  "latitude": 47.5,
  "longitude": 23.54
}

###
POST http://localhost:8080/add_storagepoint
Content-Type: application/json

{
  "name": "test2",
  "country": "test",
  "city": "test2",
  "street": "test2",
  "building": 1,
  "corpus": 1,
  "latitude": 47.9,
  "longitude": 23.84
}

###
GET http://localhost:8080/customer-orders?pageNumber=0&pageSize=2

###
GET http://localhost:8080/logout

###
POST http://localhost:8080/login
Content-Type: multipart/form-data; boundary=---------------------------218705725231419778643152202234

-----------------------------218705725231419778643152202234
Content-Disposition: form-data; name="username"

admin
-----------------------------218705725231419778643152202234
Content-Disposition: form-data; name="password"

admin

###
POST http://localhost:8080/login
Content-Type: multipart/form-data; boundary=---------------------------218705725231419778643152202234

-----------------------------218705725231419778643152202234
Content-Disposition: form-data; name="username"

qwert5

-----------------------------218705725231419778643152202234
Content-Disposition: form-data; name="password"

qwert5

###
POST http://localhost:8080/add_order
Content-Type: application/x-www-form-urlencoded

departureStoragePoint.country = Россия &
departureStoragePoint.city = Москва &
departureStoragePoint.street = Ленина &
departureStoragePoint.building = 1 &
deliveryStoragePoint.country = Россия &
deliveryStoragePoint.city = Москва &
deliveryStoragePoint.street = Ленина &
deliveryStoragePoint.building = 2 &
orderParameters.length = 1.0 &
orderParameters.width = 1.0 &
orderParameters.height = 1.0 &
orderParameters.weight = 1.0 &
time.loadingTime = 11%3A11 &
time.unloadingTime = 11%3A11 &
orderParameters.cargoType = BULK

#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="departureStoragePoint.country"
#
#Россия
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="departureStoragePoint.city"
#
#Москва
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="departureStoragePoint.street"
#
#Ленина
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="departureStoragePoint.building"
#
#1
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="deliveryStoragePoint.country"
#
#Россия
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="deliveryStoragePoint.city"
#
#Москва
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="deliveryStoragePoint.street"
#
#Ленина
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="deliveryStoragePoint.building"
#
#2
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="orderParameters.length"
#
#1.0
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="orderParameters.width"
#
#1.0
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="orderParameters.height"
#
#1.0
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="orderParameters.weight"
#
#1.0
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="time.loadingTime"
#
#11:11
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="time.unloadingTime"
#
#11:11
#-----------------------------218705725231419778643152202234
#Content-Disposition: form-data; name="orderParameters.cargoType"
#
#BULK
#-----------------------------218705725231419778643152202234--
