name: Integration tests & linting

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sql_any_changed: ${{ steps.changed-files.outputs.sql_any_changed }}
      src_any_changed: ${{ steps.changed-files.outputs.src_any_changed }}
    permissions:
      pull-requests: read
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            sql:
              - '**.sql'
            src:
              - prog/**

  # runs only when *.sql files are changed
  basic-check:
    needs: prepare
    if: needs.prepare.outputs.sql_any_changed == 'true'
    runs-on: ubuntu-latest
    container:
      image: postgres:15
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Connect to PostgreSQL
        run: |
          ./check.sh
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGPASSWORD: postgres
          PGUSER: runner
          PGOPTIONS: '--client-min-messages=warning'

  jpa-tests:
    runs-on: ubuntu-latest
    needs: prepare
    if: false
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        working-directory: ./prog/isbd-curs
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
        run: ./gradlew --no-daemon clean test
